# Generated by Django 5.2.8 on 2025-11-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
