# Generated by Django 5.2.8 on 2025-11-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopap', '0002_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
